# Generated by Django 5.1.3 on 2024-11-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='picode',
            new_name='pincode',
        ),
    ]
