# Generated by Django 5.1.3 on 2024-11-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='address1',
            new_name='shipping_address1',
        ),
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='address2',
            new_name='shipping_address2',
        ),
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='full_name',
            new_name='shipping_full_name',
        ),
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='last_name',
            new_name='shipping_last_name',
        ),
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='pincode',
            new_name='shipping_pincode',
        ),
        migrations.RenameField(
            model_name='shaippingaddress',
            old_name='state',
            new_name='shipping_state',
        ),
    ]
