# Generated by Django 5.1.3 on 2024-11-19 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_shipping_full_name_shaippingaddress_shipping_fisrt_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShaippingAddress',
            new_name='ShippingAddress',
        ),
    ]
