# Generated by Django 5.1.3 on 2024-11-19 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_shaippingaddress_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_fisrt_name',
            new_name='shipping_first_name',
        ),
    ]
