# Generated by Django 5.1.3 on 2024-11-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='amount_pay',
            new_name='amount_paid',
        ),
    ]
